# Języki Obiektowe I (Python)  - biblioteka `math`,`random` i `numpy`

###### mgr inż. Arkadiusz Banasik

### Krótka powtórka

+ poznaliśmy liczby i operacje na nich

Typ | Operacje | Metody
:---:|:---:|:---:
`int`|`+ - * / ** % //`|`is_integer()`, `abs()`
`float`|`+ - * / ** % //`|`abs()`, `round()`
`complex`|`+ - * / ** `|`.real`, `.imag`, `abs()`, `conjugate()`

Konwersja typów: `int()`, `float()`, `complex()`

+ poznaliśmy łańcuchy znaków i operacje na nich

`string = "ala ma pythona"`

Metoda/operator | Przykład
:---:|:---:
`+`|`string + string = 'ala ma pythonaala ma pythona'`
`*`|`string * 2 = 'ala ma pythonaala ma pythona'`
`string[x]`|`string[0] = 'a'`
`string[x:y]`|`string[0:3] = 'ala'`
`string[x:y:z]`|`string[0:13:2] = 'aam yhn'`
`len()`|`len(string) = 14`
`split()`|`string.split(' ') = ['ala', 'ma', 'pythona']`
`replace()`|`string.replace("pythona", "kota") = 'ala ma kota'`
`format()`|`"ala ma {} pythony".format(2) = 'ala ma 2 pythony'`
`count()`|`string.count("a") = 4`

Zamiana na typ string: `str()`

+ poznaliśmy instrukcje sterujące

```
if warunek_1:
    blok instrukcji 1
elif warunek_2:
    blok instrukcji 2
elif warunek_3:
    blok instrukcji 3
else:
    blok instrukcji 4
```

```
while warunek:
    blok instrukcji
```

```
for obiekt in obiekt_iterowalny:
    blok instrukcji
```

+ poznaliśmy listy i krotki

`lista = [1, "ala"]`

`krotka = (1, "ala")`

Metoda/operator | Przykład
:---:|:---:
`+`|`lista + lista = [1, 'ala', 1, 'ala']`, `krotka + krotka = (1, 'ala', 1, 'ala')`
`*`| `lista * 2 = [1, 'ala', 1, 'ala']`, `krotka * 2 = (1, 'ala', 1, 'ala')`
`append()`|`lista.append("ma") = [1, 'ala', 'ma']`
`remove()`|`lista.remove("ala") = [1]`
`insert()`| `lista.insert(2,"ma") = [1, 'ala', 'ma']`
`count()`|`lista.count(1) = 1`, `krotka.count(1) = 1`
`index()`|`lista.index(1) = 0`, `krotka.index(1) = 0`
`extend()`|`lista.extend(lista) = [1, 'ala', 1, 'ala']`

Z listy na krotkę: `tuple()`

Z krotki na listę: `list()`

+ poznaliśmy słowniki

`slownik = {"Imie":"Ala", "wiek":20}`

Metoda/operator | Przykład
:---:|:---:
`keys()`|`list(slownik.keys()) = ['Imie', 'wiek']`
`values()`|`list(slownik.values()) = ['Ala', 20]`
`items()`|`list(slownik.items()) = [('Imie', 'Ala'), ('wiek', 20)]`



+ zdefiniowaliśmy funkcje

```
def funkcja(parametr_1, parametr_2):
    blok instrukcji
    return wyrażenie
```

Argumenty | Przykład
:---:|:---
argumenty obowiązkowe|`funkcja(parametr_1, parametr_2)`
argumenty słowa-kluczowe|`funkcja(parametr_2=wartosc_2, parametr_1=wartosc_1)`
argumenty domyślne|`funkcja(parametr_1, parametr_2=wartosc)`
argumenty zmiennej długości|`funkcja(*lista_argumentow)`

**Funkcje anonimowe**
````
nazwa_funkcji = lambda parametr, parametr_2, ..., parametr_n : wyrażenie
````

+ poznaliśmy wyrażenia listowe

```
x = lista
y = [funkcja(i) for i in x if warunek]
```

+ poznaliśmy sposoby dołączania modułów do skryptu

Dołączanie|Przykład wykorzystania
:---:|:---:
`import moduł`|`moduł.funkcja()`
`import moduł as alias`|`alias.funkcja()`
`from moduł import *`|`funkcja()`
`from moduł import funkcja`|`funkcja()`

### Biblioteka `math`

Bibliotka oferujące podstawowe funkcje matematyczne, otoczka biblioteki `math` z języka `C`.

[https://docs.python.org/3/library/math.html](https://docs.python.org/3/library/math.html)

#### Stałe matematyczne

Stała|Opis
:---:|:---:
`pi`| $\pi$ 
`e`|$e$
`tau`|$\tau = 2\pi$, [https://www.youtube.com/watch?v=jG7vhMMXagQ](https://www.youtube.com/watch?v=jG7vhMMXagQ)
`inf`|nieskończoność numeryczna, `float('inf')`
`nan`|`NaN`, `float('nan')`

#### Funkcje numeryczne

Funkcja|Opis|Przykład
:---:|:---:|:---:|
`ceil(x)`| działa jak tradycyjny `sufit`|`ceil(-2.5)=-2`, `ceil(2.5)=3` 
`copysign(x,y)`| zwraca moduł liczby `x` ze znakiem liczby `y` czyli $\text{sgn}(y)\vert x \vert$|`copysign(3,-1)=-3` 
`fabs(x)`| działa jak tradycyjny moduł|`fabs(-3)=3` 
`factorial(x)`| zwraca `x!`|`factorial(3)=6` 
`floor(x)`| działa jak tradycyjna `podłoga`|`floor(-3.5)=-4`, `floor(3.5)=3` 
`fmod(x,y)`| zwraca $x\text{ mod }y$, zalecana przy floatach|`fmod(2.1, 1)=0.1` 
`frexp(x)`| zwraca parę (mantysa,cecha), tj. $x=mantysa\cdot 2 ^{cecha}$|`frexp(2)=(0.5, 2)` 
`fsum(obiekt iterowalny)`| zwraca sumę obiektu iterowalnego|`fsum([-0.2, -0.2])=-0.4` 

Funkcja|Opis|Przykład
:---:|:---:|:---:|
`gcd(x,y)`| zwraca $\text{nwd}(x,y)$|`gcd(4,2)=2` 
`isclose(x,y, rel_tol=1e-09, abs_tol=0.0)`| sprawdza, czy `x` i `y` są bliskie, zgodnie z zadaną tolerancją|`isclose(2, 2.00000001)=False`, `isclose(2, 2.000000001)=True` 
`isfinite(x)`| zwraca `True` jeśli `x` nie jest nieskończonością albo `NaN`|`isfinite(math.inf)=False` 
`isinf(x)`| zwraca `True` jeśli x jest $\pm$ nieskończonością|`isinf(math.inf)=True` 
`isnan(x)`| zwraca `True` jeśli x jest `NaN`|`isnan(float('nan'))=True` 
`ldexp(x,i)`| zwraca $y=x2^i$, odwrotność funkcji `frexp(y)` |`ldexp(0.5,2)=2` 
`modf(x)`| zwraca parę (część całkowita, część ułamkowa) |`modf(2.5)=(0.5,2.0)` 

#### Funkcje wykładnicze i logarytmiczne

Funkcja|Opis|Przykład
:---:|:---:|:---:|
`exp(x)`| zwraca $e^x$|`exp(0)=1.0` 
`expm1(x)`| zwraca $e^x-1$, przydatna dla małych wartości $x$|`exp(1e-5)=1.0000050000166667e-05` 
`log(x,b)`| zwraca $\log_{b}x$, domyślnie $b=e$| `log(math.e)=1.0`, `log(4,2)=2.0` 
`log2(x)`| zwraca $\log_2 x$|`log2(4)=2.0` 
`log10(x)`| zwraca $\log_{10} x$|`log10(10)=1.0` 
`pow(x,y)`| zwraca $x^y$|`pow(2, 4)=16.0` 
`sqrt(x)`| zwraca $\sqrt{x}$|`sqrt(4)=2.0` 

#### Funkcje trygonometryczne, cyklometryczne, zamiana kątów

Funkcja|Opis|Przykład
:---:|:---:|:---:|
`acos(x)`| zwraca $\arccos{x}$|`acos(0)=1.5707963267948966` 
`asin(x)`| zwraca $\arcsin{x}$|`asin(1)=1.5707963267948966` 
`atan(x)`| zwraca $\arctan{x}$|`atan(1)=0.7853981633974483` 
`cos(x)`| zwraca $\cos{x}$|`cos(1)=1.0` 
`degrees(x)`| zamienia radiany na stopnie|`degrees(math.pi/2)=90.0` 
`hypot(x,y)`| zwraca moduł liczby zespolonej $x+iy$|`hypot(1, 1)=1.4142135623730951` 
`radians(x)`| zamienia stopnie na radiany|`radians(180)=3.141592653589793`
`sin(x)`| zwraca $\sin{x}$|`sin(0)=0.0` 
`tan(x)`| zwraca $\tan{x}$|`tan(0)=0.0` 

#### Funkcje hiperboliczne i area

Funkcja|Opis|Przykład
:---:|:---:|:---:
`acosh(x)`| zwraca $\text{acosh}x$|`acosh(1)=0.0`
`asinh(x)`| zwraca $\text{asinh}x$|`asinh(0)=0.0`
`atanh(x)`| zwraca $\text{asinh}x$|`atanh(0)=0.0`
`cosh(x)`| zwraca $\text{cosh}x$|`cosh(0)=1.0`
`tanh(x)`| zwraca $\text{tanh}x$|`tanh(0)=0.0`

#### Funkcje specjalne

Funkcja|Opis
:---:|:---:
`erf(x)`| funkcja błędu, $erf(x) = \frac{2}{\sqrt{\pi}}\int\limits_0^x e^{-t^2} dt$
`erfc(x)`| uzupełniająca funkcja błędu, $erfc(x) =1-erf(x)=1- \frac{2}{\sqrt{\pi}}\int\limits_x^{\infty} e^{-t^2} dt$
`gamma(x)`| funkcja Gamma, $\Gamma (x) = \int\limits_0^{\infty} x^{z-1}e^{-x} dx  \text{ dla  }  Re(z) > 0$

### Biblioteka `random`

Zawiera metody do generowania wartości (pseudo)losowych z różnych rozkładów.
[https://www.random.org/analysis/](https://www.random.org/analysis/)

#### Generowanie wartości całkowitych

Funkcja|Opis
:---:|:---:
`randint(a, b)`| zwraca wartość całkowitą z przedziału $[a,b]$
`range(a, b, krok)`| zwraca wartość całkowitą z przedziału $[a,b]$ z odpowiednim `krokiem`

#### Generowanie wartości zmiennoprzecinkowych

Funkcja|Opis
:---:|:---:
`random()`| zwraca wartość z przedziału $[0,1]$
`uniform(a, b)`| zwraca wartość z przedziału $[a,b]$ 
`triangular(a, b, moda)` | zwraca wartość z przedziału $[a,b]$ z modą w punkcie `moda`
`expovariate(lambd)`|zwraca wartość z rozkładu wykładniczego z $\lambda$ = `lambda`
`gauss(srednia, odchylenie)`|zwraca wartość z rozkładu normalnego z odpowiednią `średnią` i `odchyleniem`
`paretovariate(alpha)`|zwraca wartość z rozkładu Pareto z parametrem kształtu `alpha`
`weibullvariate(alpha, beta)`|zwraca wartość z rozkładu Wiebulla z parametrem skali = `alpha` i parametrem kształtu = `beta`

#### Metody dla zbiorów

Funkcja|Opis|Przykład
:---:|:---:|:---:
`choice(zbiór)`| zwraca wartość z podanego `zbioru`|`choice(["ala", "ma", "kota"])='ala'`
`choices(zbiór, wagi, k=1)`|zwraca `k` wartości z powtórzniami ze `zbioru` z uzględnieniem `wag` |`choices(["ala", "ma", "kota"], [0.1,0.1, 0.8])=['kota']`
`shuffle(zbiór)`|permutuje elementy zbioru|`zb=["ala", "ma", "kota"] shuffle(zb) zb=['kota', 'ma', 'ala']`
`sample(zbiór, k)`|zwraca `k` elementów bez powtórzeń ze `zbioru`|`sample(["ala", "ma", "kota"], k=2)=['ma', 'kota']`

### Biblioteka `numpy`
Biblioteka numeryczna `Pythona`.

[http://www.numpy.org/](http://www.numpy.org/)

### Tablice i macierze w `numpy`

###### `array()`

W przeciwieństwie do tablic pythonowych `numpy` dostarcza potężnych narzędzi do pracy z listami i macierzami ale wymaga, by elementy tych struktur miały ten sam typ. 

In [4]:
import numpy as np

lista = np.array([1, 2, 3, 4, 5])

print(lista)

[1 2 3 4 5]


In [5]:
print(np.array([3.14, 2, 3, 4, 5]))

[3.14 2.   3.   4.   5.  ]


In [6]:
macierz = np.array([[1, 2], [3, 4]])

print(macierz)

[[1 2]
 [3 4]]


In [7]:
macierz = np.array([range(i, i + 3) for i in [1, 4, 7]])

print(macierz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### `zeros()`, `ones()` i `full()`

In [9]:
macierz_1 = np.zeros(10)
macierz_2 = np.ones(10)
macierz_3 = np.full(10, 3.14)

print(macierz_1)
print(macierz_2)
print(macierz_3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [8]:
macierz_1 = np.zeros((2,3), dtype=int)
macierz_2 = np.ones((3,2), dtype=bool)
macierz_3 = np.full((3,3), 3.14, dtype=int)

print(macierz_1)
print(macierz_2)
print(macierz_3)

[[0 0 0]
 [0 0 0]]
[[ True  True]
 [ True  True]
 [ True  True]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


##### `arange()` i `linspace()`

In [11]:
wektor = np.arange(0, 10, 2)

print(wektor)

[0 2 4 6 8]


In [12]:
wektor = np.linspace(0, 1, 10)

print(wektor)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [13]:
wektor = np.linspace(0, 1, 10, endpoint=False)

print(wektor)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


##### `eye()`

In [14]:
macierz = np.eye(3)

print(macierz)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### Atrybuty macierzy

##### `ndim`, `shape`, `size`

In [15]:
macierz = np.array([range(i, i + 3) for i in [1, 4, 7]])

print(macierz)
print(macierz.ndim)
print(macierz.shape)
print(macierz.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


##### Dostęp do elementów macierzy

In [9]:
macierz = np.array([range(i, i + 3) for i in [1, 4, 7]])

print(macierz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(macierz[0])

[1 2 3]


In [11]:
print(macierz[0, 0])

1


In [12]:
print(macierz[0][0])

1


In [20]:
print(macierz[-1])

[7 8 9]


In [21]:
print(macierz[0, -1])

3


##### Cięcie macierzy

In [22]:
wektor = x = np.arange(10)

print(wektor)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print(wektor[:7])

[0 1 2 3 4 5 6]


In [24]:
print(wektor[7:])

[7 8 9]


In [25]:
print(wektor[1:7])

[1 2 3 4 5 6]


In [26]:
print(wektor[1:7:2])

[1 3 5]


In [27]:
print(wektor[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [28]:
macierz = np.array([range(i, i + 3) for i in [1, 4, 7]])

print(macierz[:2, :2])

[[1 2]
 [4 5]]


In [29]:
print(macierz[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [30]:
print(macierz[:2, ::2])

[[1 3]
 [4 6]]


In [31]:
print(macierz[:, 0])

[1 4 7]


##### Zmiana wartości elementu

In [32]:
macierz[0,0] = -1

print(macierz)

[[-1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


##### Kopiowanie macierzy

##### `copy()`

In [33]:
macierz_1 = np.array([range(i, i + 3) for i in [1, 4, 7]])
macierz_2 = macierz_1.copy()

macierz_1[0,0] = -1

print(macierz_1)
print(macierz_2)

[[-1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Zmiana wymiaru macierzy
##### `reshape()`

In [34]:
import numpy as np

macierz = np.arange(1, 10).reshape(3, 3)

print(macierz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
macierz = np.arange(1, 10)
print(macierz)

[1 2 3 4 5 6 7 8 9]


In [36]:
macierz = np.arange(1, 10).reshape((9, 1))

print(macierz)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


##### Maskowanie

In [14]:
macierz = np.arange(100).reshape(10,10)
macierz

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
m = (macierz > 30) & (macierz < 51)
macierz[m]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50])

##### Łączenie macierzy

##### `concatenate()`

In [39]:
macierz_1 = np.array([1, 2, 3])
macierz_2 = np.array([4, 5, 6])

macierz_3 = np.concatenate([macierz_1, macierz_2])
print(macierz_3)

[1 2 3 4 5 6]


##### Dzielenie macierzy

##### `split()`

In [40]:
macierz = np.arange(9)
macierz_1, macierz_2, macierz_3 = np.split(macierz, [2, 6])
print(macierz_1)
print(macierz_2)
print(macierz_3)

[0 1]
[2 3 4 5]
[6 7 8]


### Wybrane operacje na macierzach

##### Macierze i  skalary

In [41]:
macierz = np.arange(4).reshape((2,2))

print("macierz     =", macierz)
print("macierz + 2 =", macierz + 2)
print("macierz - 2 =", macierz - 2)
print("macierz * 2 =", macierz * 2)
print("macierz / 2 =", macierz / 2)
print("macierz ** 2 =", macierz ** 2)
print("macierz % 2 =", macierz % 2)
print("macierz // 2 =", macierz // 2)

macierz     = [[0 1]
 [2 3]]
macierz + 2 = [[2 3]
 [4 5]]
macierz - 2 = [[-2 -1]
 [ 0  1]]
macierz * 2 = [[0 2]
 [4 6]]
macierz / 2 = [[0.  0.5]
 [1.  1.5]]
macierz ** 2 = [[0 1]
 [4 9]]
macierz % 2 = [[0 1]
 [0 1]]
macierz // 2 = [[0 0]
 [1 1]]


In [42]:
macierz_1 = -(2 * macierz - 1) ** 2

print(macierz)
print(macierz_1)

[[0 1]
 [2 3]]
[[ -1  -1]
 [ -9 -25]]


`macierz = np.array([1, 2])`

Operator|Metoda|Przykład
:---:|:---:|:---:
`+`|	`add()`|	`np.add(macierz, 2) = [3 4]`
`-`|	`subtract()`|	`np.subtract(macierz, 2) = [-1  0]`
`-`|	`negative()`|	`np.negative(macierz) = [-1 -2]`
`*`|	`multiply()`|	`np.multiply(macierz, 2) = [2 4]`
`/`|	`divide()`|	`np.divide(macierz, 2) = [0.5 1. ]`
`//`|	`floor_divide()`|	`np.floor_divide(macierz, 2) = [0 1]`
`**`|	`power()`|	`np.power(macierz, 2) = [1 4]`
`%`|	`mod()`|	`np.mod(macierz, 2) = [1 0]`

##### `abs()`

In [43]:
macierz = np.array([-1, 2])

print(np.abs(macierz))

[1 2]


In [44]:
macierz = np.array([-1 + 1j, 1 - 1J])

print(np.abs(macierz))

[1.41421356 1.41421356]


##### Macierze z macierzami

##### `array_equal()`

In [16]:
macierz_1 = np.eye(2)
macierz_2 = [[1,0], [0,1]]
np.array_equal(macierz_1,macierz_2)

True

In [46]:
macierz_1 = np.arange(4).reshape((2,2))
macierz_2 = np.eye(2)

print("macierz_1=\n", macierz_1, '\nmacierz_2=\n', macierz_2, '\nmacierz_1 + macierz_2=\n', macierz_1 + macierz_2 )

macierz_1=
 [[0 1]
 [2 3]] 
macierz_2=
 [[1. 0.]
 [0. 1.]] 
macierz_1 + macierz_2=
 [[1. 1.]
 [2. 4.]]


##### `dot()`

In [47]:
macierz_1 = np.arange(4).reshape((2,2))
macierz_2 = np.eye(2)

print("macierz_1=\n", macierz_1, '\nmacierz_2=\n', 
      macierz_2, '\nmacierz_1 * macierz_2=\n', np.dot(macierz_1, macierz_2) )

macierz_1=
 [[0 1]
 [2 3]] 
macierz_2=
 [[1. 0.]
 [0. 1.]] 
macierz_1 * macierz_2=
 [[0. 1.]
 [2. 3.]]


In [48]:
macierz_1 = np.arange(4).reshape((2,2))
macierz_2 = np.eye(2)

print("macierz_1=\n", macierz_1, '\nmacierz_2=\n', 
      macierz_2, '\nmacierz_1 * macierz_2=\n', macierz_1@macierz_2 )

macierz_1=
 [[0 1]
 [2 3]] 
macierz_2=
 [[1. 0.]
 [0. 1.]] 
macierz_1 * macierz_2=
 [[0. 1.]
 [2. 3.]]


##### trace()

In [49]:
macierz = np.arange(4).reshape((2,2))

print(macierz)
print(np.trace(macierz))

[[0 1]
 [2 3]]
3


##### Moduł `numpy.linalg()`

[https://docs.scipy.org/doc/numpy/reference/routines.linalg.html](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

##### Wybrane metody

##### matrix_power()

In [50]:
import numpy.linalg as lg

macierz = np.arange(4).reshape((2,2))

macierz_kw = lg.matrix_power(macierz, 2)

print(macierz_kw)
print(np.dot(macierz, macierz))

[[ 2  3]
 [ 6 11]]
[[ 2  3]
 [ 6 11]]


##### eig()

In [51]:
macierz = [[1,0], [0,2]]

wartości_własne = lg.eig(macierz)

print(wartości_własne)

(array([1., 2.]), array([[1., 0.],
       [0., 1.]]))


##### det()

In [52]:
macierz = [[1,0], [0,2]]
print(macierz)
wyznacznik = lg.det(macierz)

print(wyznacznik)

[[1, 0], [0, 2]]
2.0


##### matrix_rank()

In [53]:
macierz_1 = [[1,0], [0,2]]
macierz_2 = [[1,0], [1,0]]

print(lg.matrix_rank(macierz_1))
print(lg.matrix_rank(macierz_2))

2
1


##### inv()

In [54]:
macierz = np.arange(4).reshape((2,2))

odwrotna = lg.inv(macierz)

print(odwrotna)
print(np.dot(macierz, odwrotna))

[[-1.5  0.5]
 [ 1.   0. ]]
[[1. 0.]
 [0. 1.]]


##### solve()

In [55]:
A = [[1,2],[-1,1]]
b = [-1, -2]

rozwiązanie = lg.solve(A,b)

print(rozwiązanie)

[ 1. -1.]


##### Statystyka opisowa z `numpy`

[https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.statistics.html](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.statistics.html)

##### mean()

In [56]:
A = list(range(4))

print(A)

średnia = np.mean(A)
print(średnia)

[0, 1, 2, 3]
1.5


In [57]:
A = np.arange(4).reshape((2,2))

print(A)

średnia = np.mean(A)
print(średnia)

[[0 1]
 [2 3]]
1.5


In [58]:
średnia_1 = np.mean(A, axis=0)
print(średnia_1)

[1. 2.]


In [59]:
średnia_2 = np.mean(A, axis=1)
print(średnia_2)

[0.5 2.5]


##### std()

In [60]:
A = list(range(4))

print(A)

std = np.std(A)
print(std)

[0, 1, 2, 3]
1.118033988749895


In [61]:
A = np.arange(4).reshape((2,2))

print(A)

std = np.std(A)
print(std)

[[0 1]
 [2 3]]
1.118033988749895


In [62]:
std_1 = np.std(A, axis=0)
print(std_1)

[1. 1.]


In [63]:
std_2 = np.std(A, axis=1)
print(std_2)

[0.5 0.5]


##### var()

In [64]:
A = list(range(4))

print(A)

wariancja = np.var(A)
print(wariancja)

[0, 1, 2, 3]
1.25


In [65]:
A = np.arange(4).reshape((2,2))

print(A)

wariancja = np.var(A)
print(wariancja)

[[0 1]
 [2 3]]
1.25


In [66]:
wariancja_1 = np.var(A, axis=0)
print(wariancja_1)

[1. 1.]


In [67]:
wariancja_2 = np.var(A, axis=1)
print(wariancja_2)

[0.25 0.25]


##### median()

In [68]:
A = list(range(5))

print(A)

mediana = np.median(A)
print(mediana)

[0, 1, 2, 3, 4]
2.0


In [69]:
A = np.arange(4).reshape((2,2))

print(A)

mediana = np.median(A)
print(mediana)

[[0 1]
 [2 3]]
1.5


In [70]:
mediana_1 = np.median(A, axis=0)
print(mediana_1)

[1. 2.]


In [71]:
mediana_2 = np.median(A, axis=1)
print(mediana_2)

[0.5 2.5]


##### Macierz losowa

In [24]:
macierz = np.random.randint(-10,10, (2, 2))
macierz

array([[ 8,  1],
       [-9, -1]])

### Dziękuję za uwagę :)